version: '3.3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.pgdb
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '0220'
      POSTGRES_DB: 'fcn'
    container_name: fcn-postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - fcn_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fcn-pgadmin
    restart: always
    ports: 
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: 'rubymagoo@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '74870220'

    networks:
      - fcn_network

networks:
  fcn_network:
    external: true

volumes:
  postgres-data:
  pgadmin-data:
